### ISSUE TITLE
Error: Call to undefined method SamlAuthenticate::unauthenticated() File: /Users/teammember/Sites/sicake/lib/Cake/Controller/Component/AuthComponent.php Line: 345

### ISSUE THREAD

**Issue by smichaelp** [zl4bv/CakePHP-simpleSAMLphp-Plugin#1]
I'm new to Cake and simpleSAMLphp.  I have simpleSAMLphp running properly because I have it working with WordPress SSO Plugin.  

So, I'm trying to figure out why I get this error when I follow your directions.  Is the newest version of Cake too new for this plugin?

Error: Call to undefined method SamlAuthenticate::unauthenticated() File: /Users/teammember/Sites/sicake/lib/Cake/Controller/Component/AuthComponent.php Line: 345

**Comment by zl4bv** [comment]
Thank you for taking the time to report this issue.

As you say, Cake has introduced new features in Cake 2.4 that this plugin does not support. 

I have added the new functionality to the plugin. Please test that it works with your application and provide feedback so that I can confirm that this issue has been resolved.

**Comment by smichaelp** [comment]
Thanks!  It seems to be working better now.  I was able to get it to work per controller method yesterday.  But, I went ahead and tested out your updates and all is well.

public $components = array('Saml.Saml');
